version: '3.4'

services:
  api:
    image: friends_friends-api
    depends_on:
      - user-service
      - group-service
    env_file:
      - ./friends.env
    environment:
      PORT: 8000
    ports:
      - 8000:8000

  user-service:
    image: friends_user-service
    depends_on:
      - outgoing-proxy-service
    env_file:
    - ./friends.env
    environment:
      PORT: 8000
    ports:
      - 8001:8000

  group-service:
    image: friends_group-service
    depends_on:
      - mongo
    env_file:
      - ./friends.env
    environment:
      PORT: 8000
      MONGO_FEATURE_COLLECTION_NAME: groups
    ports:
      - 8002:8000

  outgoing-proxy-service:
    image: spike-proxy-service-master
    env_file:
      - ./friends.env
    environment:
      MODE: outgoing
      PORT: 8000
    ports:
      - 8003:8000

  incoming-spike-proxy:
    image: spike-proxy-service-master
    env_file:
      - ./friends.env
    environment: 
      MODE: incoming
      PORT: 8000
    ports:
      - 8004:8000

  mongo:
    image: "mongo:4.0.9"
    ports:
      - "27017:27017"
    volumes:
      - "./data/db:/data/db"

  redis:
    image: redis
    ports:
      - 6379:6379

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.5.0"
    environment:
      - discovery.type=single-node
    container_name: elasticsearch
    ports:
      - "9200:9200"

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.5.0"
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  apm:
    image: "docker.elastic.co/apm/apm-server:7.5.0"
    container_name: apm
    ports:
      - "8200:8200"
    depends_on:
      - elasticsearch

  auth-service:
    container_name: friends-auth-service
    image: friends_friends-auth-service
    env_file:
      - ./friends.env
    environment:
      SPIKE_CLIENT_ID: StxnQ0vCvXSZU594sd3IsjOGG3oejz1gCDMHtiUc
      SPIKE_CLIENT_SECRET: MQ9aTAgdTs88hq1VVzW3_66Rsv2hyc57a9O9Pf1DCvs_cjOr2FGDVsDplFd9Ul5acem28npIcZdealx9_8qXbKHw5aFYyRt70wuG
    ports:
      - 8005:8000

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - 8443:8443
    volumes:
      - ./authorization-service/nginx:/etc/nginx/conf.d
    depends_on:
      - auth-service

  config-service:
    image: friends_friends-config-server
    env_file:
      - ./friends.env
    environment:
      PORT: 8000
      API_GATEWAY_URI: http://localhost:8004/
      AUTH_SERVICE_URI: http://localhost:8005/
    ports:
      - 4000:8000

  client:
    image: friends_client
    ports:
      - '3000:3000'